/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    AppBreadcrumbs: typeof import('./src/components/layout/AppBreadcrumbs.vue')['default']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    BestSellingSidebar: typeof import('./src/components/sections/BestSellingSidebar.vue')['default']
    CategorySection: typeof import('./src/components/sections/CategorySection.vue')['default']
    DocumentList: typeof import('./src/components/sections/DocumentList.vue')['default']
    FloatingContact: typeof import('./src/components/layout/FloatingContact.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroSection: typeof import('./src/components/sections/HeroSection.vue')['default']
    HomeShowcase: typeof import('./src/components/sections/HomeShowcase.vue')['default']
    NewsList: typeof import('./src/components/sections/NewsList.vue')['default']
    PartnerGrid: typeof import('./src/components/sections/PartnerGrid.vue')['default']
    ProductBlocks: typeof import('./src/components/sections/ProductBlocks.vue')['default']
    ProductDetailPage: typeof import('./src/components/sections/ProductDetailPage.vue')['default']
    ProductSection: typeof import('./src/components/sections/ProductSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteFooter: typeof import('./src/components/layout/SiteFooter.vue')['default']
    SiteHeader: typeof import('./src/components/layout/SiteHeader.vue')['default']
  }
}
